### ISSUE TITLE
Thanks, and a question for incremental packaging?

### ISSUE THREAD

**Issue by farnking** [mobiusklein/cython_pyinstaller_example#3]
Hi, dear Mobius: 

Thank you for the wonder and crispy tutorial.  
I have one question regarding the packaging time.  
In this example, an exe file will be created together with some so or dll files.  
Do those dll or so files include, say in windows, app.dll and calc.dll ?
If they do, can I next time just some generated app.dll and calc.dll and send these two files to the client for update?
Or do I still have to run pyinstaller through all steps of the compilation and import-tracking for the next package update?

**Comment by mobiusklein** [comment]
You have to repeat all those steps and re-distribute the entire bundle. You cannot guarantee those other files haven't changed. There are tools like https://github.com/dennisvang/tufup (or the now defunct https://github.com/Digital-Sapphire/PyUpdater/) can make the redistribution process less difficult, but it is still labor-intensive.

**Comment by farnking** [comment]
Thanks for the reply.   I wanna insert some signature to the distribution for each client so that the clients cannot pirate-copy my distribution.  But then it may cost a lot of time to construct the distribute for each individual client since my source code is like 100K lines.  Your suggestions will be appreciated.

**Comment by mobiusklein** [comment]
If you need that level of protection, you could either look at https://github.com/dashingsoft/pyarmor, or implement some sort of license key mechanism. The license key might just be an encrypted file that the program reads to determine if the user is valid, or it might be something you need to validate with some kind of server you operate to verify number of valid users associated with that license key.

Neither of those is within the scope of this tutorial, nor are they something I've done myself.

**Comment by farnking** [comment]
Thanks, have a good Halloween!
